include: package:very_good_analysis/analysis_options.yaml



analyzer:
  errors:
    avoid_print: ignore
    flutter_style_todos: ignore
    public_member_api_docs: ignore

  # plugins:
  #   - custom_lint
#TODO: Remove avoid_print
