include: package:very_good_analysis/analysis_options.yaml


#TODO: Remove avoid_print
analyzer:
  errors:

    # avoid_print: ignore
    document_ignores: ignore
    flutter_style_todos: ignore
    prefer_int_literals: ignore
    public_member_api_docs: ignore



