name: foods_app
description: "An app the search the usda foods db"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  auto_hyphenating_text: ^0.3.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  # flutter_svg: ^2.0.10+1

  mocktail: ^1.0.4
  shared_preferences: ^2.3.2
  units_converter: ^3.0.2
  usda_db_package:
   git:
     url: https://github.com/marshall-buck/usda_db_package.git
  watch_it: ^1.5.0


dev_dependencies:
  build_runner: ^2.4.12
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
