name: foods_app
description: "An app the search the usda foods db"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  usda_db_package:
    git:
      url: https://github.com/marshall-buck/usda_db_package.git
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  watch_it: ^1.4.2
  mocktail: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.11
  fake_async: ^1.3.1

flutter:
  uses-material-design: true
